/** Modificacion Pais de Origen **/

UPDATE `productos` SET `pais_origen` = 'AF' WHERE (`pais_origen` = "Afghanistan");
UPDATE `productos` SET `pais_origen` = 'AX' WHERE (`pais_origen` = "Aland Islands");
UPDATE `productos` SET `pais_origen` = 'AL' WHERE (`pais_origen` = "Albania");
UPDATE `productos` SET `pais_origen` = 'DZ' WHERE (`pais_origen` = "Algeria");
UPDATE `productos` SET `pais_origen` = 'AS' WHERE (`pais_origen` = "American Samoa");
UPDATE `productos` SET `pais_origen` = 'AD' WHERE (`pais_origen` = "Andorra");
UPDATE `productos` SET `pais_origen` = 'AO' WHERE (`pais_origen` = "Angola");
UPDATE `productos` SET `pais_origen` = 'AI' WHERE (`pais_origen` = "Anguilla");
UPDATE `productos` SET `pais_origen` = 'AQ' WHERE (`pais_origen` = "Antarctica");
UPDATE `productos` SET `pais_origen` = 'AG' WHERE (`pais_origen` = "Antigua and Barbuda");
UPDATE `productos` SET `pais_origen` = 'AR' WHERE (`pais_origen` = "Argentina");
UPDATE `productos` SET `pais_origen` = 'AM' WHERE (`pais_origen` = "Armenia");
UPDATE `productos` SET `pais_origen` = 'AW' WHERE (`pais_origen` = "Aruba");
UPDATE `productos` SET `pais_origen` = 'AU' WHERE (`pais_origen` = "Australia");
UPDATE `productos` SET `pais_origen` = 'AT' WHERE (`pais_origen` = "Austria");
UPDATE `productos` SET `pais_origen` = 'AZ' WHERE (`pais_origen` = "Azerbaijan");
UPDATE `productos` SET `pais_origen` = 'BS' WHERE (`pais_origen` = "Bahamas");
UPDATE `productos` SET `pais_origen` = 'BH' WHERE (`pais_origen` = "Bahrain");
UPDATE `productos` SET `pais_origen` = 'BD' WHERE (`pais_origen` = "Bangladesh");
UPDATE `productos` SET `pais_origen` = 'BB' WHERE (`pais_origen` = "Barbados");
UPDATE `productos` SET `pais_origen` = 'BY' WHERE (`pais_origen` = "Belarus");
UPDATE `productos` SET `pais_origen` = 'BE' WHERE (`pais_origen` = "Belgium");
UPDATE `productos` SET `pais_origen` = 'BZ' WHERE (`pais_origen` = "Belize");
UPDATE `productos` SET `pais_origen` = 'BJ' WHERE (`pais_origen` = "Benin");
UPDATE `productos` SET `pais_origen` = 'BM' WHERE (`pais_origen` = "Bermuda");
UPDATE `productos` SET `pais_origen` = 'BT' WHERE (`pais_origen` = "Bhutan");
UPDATE `productos` SET `pais_origen` = 'BO' WHERE (`pais_origen` = "Bolivia");
UPDATE `productos` SET `pais_origen` = 'BQ' WHERE (`pais_origen` = "Bonaire, Sint Eustatius and Saba");
UPDATE `productos` SET `pais_origen` = 'BA' WHERE (`pais_origen` = "Bosnia and Herzegovina");
UPDATE `productos` SET `pais_origen` = 'BW' WHERE (`pais_origen` = "Botswana");
UPDATE `productos` SET `pais_origen` = 'BV' WHERE (`pais_origen` = "Bouvet Island");
UPDATE `productos` SET `pais_origen` = 'BR' WHERE (`pais_origen` = "Brazil");
UPDATE `productos` SET `pais_origen` = 'BR' WHERE (`pais_origen` = "Brasil");
UPDATE `productos` SET `pais_origen` = 'IO' WHERE (`pais_origen` = "British Indian Ocean Territory");
UPDATE `productos` SET `pais_origen` = 'BN' WHERE (`pais_origen` = "Brunei Darussalam");
UPDATE `productos` SET `pais_origen` = 'BG' WHERE (`pais_origen` = "Bulgaria");
UPDATE `productos` SET `pais_origen` = 'BF' WHERE (`pais_origen` = "Burkina Faso");
UPDATE `productos` SET `pais_origen` = 'BI' WHERE (`pais_origen` = "Burundi");
UPDATE `productos` SET `pais_origen` = 'CV' WHERE (`pais_origen` = "Cambodia");
UPDATE `productos` SET `pais_origen` = 'KH' WHERE (`pais_origen` = "Cameroon");
UPDATE `productos` SET `pais_origen` = 'CM' WHERE (`pais_origen` = "Canada");
UPDATE `productos` SET `pais_origen` = 'CA' WHERE (`pais_origen` = "Cape Verde");
UPDATE `productos` SET `pais_origen` = 'KY' WHERE (`pais_origen` = "Cayman Islands");
UPDATE `productos` SET `pais_origen` = 'CF' WHERE (`pais_origen` = "Central African Republic");
UPDATE `productos` SET `pais_origen` = 'TD' WHERE (`pais_origen` = "Chad");
UPDATE `productos` SET `pais_origen` = 'CL' WHERE (`pais_origen` = "Chile");
UPDATE `productos` SET `pais_origen` = 'CN' WHERE (`pais_origen` = "China");
UPDATE `productos` SET `pais_origen` = 'CX' WHERE (`pais_origen` = "Christmas Island");
UPDATE `productos` SET `pais_origen` = 'CC' WHERE (`pais_origen` = "Cocos (Keeling) Islands");
UPDATE `productos` SET `pais_origen` = 'CO' WHERE (`pais_origen` = "Colombia");
UPDATE `productos` SET `pais_origen` = 'KM' WHERE (`pais_origen` = "Comoros");
UPDATE `productos` SET `pais_origen` = 'CD' WHERE (`pais_origen` = "Congo");
UPDATE `productos` SET `pais_origen` = 'CG' WHERE (`pais_origen` = "Congo, The Democratic Republic of ");
UPDATE `productos` SET `pais_origen` = 'CK' WHERE (`pais_origen` = "Cook Islands");
UPDATE `productos` SET `pais_origen` = 'CR' WHERE (`pais_origen` = "Costa Rica");
UPDATE `productos` SET `pais_origen` = 'CI' WHERE (`pais_origen` = "Cote d'Ivoire");
UPDATE `productos` SET `pais_origen` = 'HR' WHERE (`pais_origen` = "Croatia");
UPDATE `productos` SET `pais_origen` = 'CU' WHERE (`pais_origen` = "Cuba");
UPDATE `productos` SET `pais_origen` = 'CW' WHERE (`pais_origen` = "Curaçao");
UPDATE `productos` SET `pais_origen` = 'CY' WHERE (`pais_origen` = "Cyprus");
UPDATE `productos` SET `pais_origen` = 'CZ' WHERE (`pais_origen` = "Czechia");
UPDATE `productos` SET `pais_origen` = 'DK' WHERE (`pais_origen` = "Denmark");
UPDATE `productos` SET `pais_origen` = 'DJ' WHERE (`pais_origen` = "Djibouti");
UPDATE `productos` SET `pais_origen` = 'DM' WHERE (`pais_origen` = "Dominica");
UPDATE `productos` SET `pais_origen` = 'DO' WHERE (`pais_origen` = "Dominican Republic");
UPDATE `productos` SET `pais_origen` = 'EC' WHERE (`pais_origen` = "Ecuador");
UPDATE `productos` SET `pais_origen` = 'EG' WHERE (`pais_origen` = "Egypt");
UPDATE `productos` SET `pais_origen` = 'SV' WHERE (`pais_origen` = "El Salvador");
UPDATE `productos` SET `pais_origen` = 'GQ' WHERE (`pais_origen` = "Equatorial Guinea");
UPDATE `productos` SET `pais_origen` = 'ER' WHERE (`pais_origen` = "Eritrea");
UPDATE `productos` SET `pais_origen` = 'EE' WHERE (`pais_origen` = "Estonia");
UPDATE `productos` SET `pais_origen` = 'ET' WHERE (`pais_origen` = "Ethiopia");
UPDATE `productos` SET `pais_origen` = 'FK' WHERE (`pais_origen` = "Falkland Islands (Malvinas)");
UPDATE `productos` SET `pais_origen` = 'FO' WHERE (`pais_origen` = "Faroe Islands");
UPDATE `productos` SET `pais_origen` = 'FJ' WHERE (`pais_origen` = "Fiji");
UPDATE `productos` SET `pais_origen` = 'FI' WHERE (`pais_origen` = "Finland");
UPDATE `productos` SET `pais_origen` = 'FR' WHERE (`pais_origen` = "France");
UPDATE `productos` SET `pais_origen` = 'GF' WHERE (`pais_origen` = "French Guiana");
UPDATE `productos` SET `pais_origen` = 'PF' WHERE (`pais_origen` = "French Polynesia");
UPDATE `productos` SET `pais_origen` = 'TF' WHERE (`pais_origen` = "French Southern Territories");
UPDATE `productos` SET `pais_origen` = 'GA' WHERE (`pais_origen` = "Gabon");
UPDATE `productos` SET `pais_origen` = 'GM' WHERE (`pais_origen` = "Gambia");
UPDATE `productos` SET `pais_origen` = 'GE' WHERE (`pais_origen` = "Georgia");
UPDATE `productos` SET `pais_origen` = 'DE' WHERE (`pais_origen` = "Germany");
UPDATE `productos` SET `pais_origen` = 'GH' WHERE (`pais_origen` = "Ghana");
UPDATE `productos` SET `pais_origen` = 'GI' WHERE (`pais_origen` = "Gibraltar");
UPDATE `productos` SET `pais_origen` = 'GR' WHERE (`pais_origen` = "Greece");
UPDATE `productos` SET `pais_origen` = 'GL' WHERE (`pais_origen` = "Greenland");
UPDATE `productos` SET `pais_origen` = 'GD' WHERE (`pais_origen` = "Grenada");
UPDATE `productos` SET `pais_origen` = 'GP' WHERE (`pais_origen` = "Guadeloupe");
UPDATE `productos` SET `pais_origen` = 'GU' WHERE (`pais_origen` = "Guam");
UPDATE `productos` SET `pais_origen` = 'GT' WHERE (`pais_origen` = "Guatemala");
UPDATE `productos` SET `pais_origen` = 'GG' WHERE (`pais_origen` = "Guernsey");
UPDATE `productos` SET `pais_origen` = 'GN' WHERE (`pais_origen` = "Guinea");
UPDATE `productos` SET `pais_origen` = 'GW' WHERE (`pais_origen` = "Guinea-Bissau");
UPDATE `productos` SET `pais_origen` = 'GY' WHERE (`pais_origen` = "Guyana");
UPDATE `productos` SET `pais_origen` = 'HT' WHERE (`pais_origen` = "Haiti");
UPDATE `productos` SET `pais_origen` = 'HM' WHERE (`pais_origen` = "Heard and Mc Donald Islands");
UPDATE `productos` SET `pais_origen` = 'VA' WHERE (`pais_origen` = "Holy See (Vatican City State)");
UPDATE `productos` SET `pais_origen` = 'HN' WHERE (`pais_origen` = "Honduras");
UPDATE `productos` SET `pais_origen` = 'HK' WHERE (`pais_origen` = "Hong Kong");
UPDATE `productos` SET `pais_origen` = 'HU' WHERE (`pais_origen` = "Hungary");
UPDATE `productos` SET `pais_origen` = 'IS' WHERE (`pais_origen` = "Iceland");
UPDATE `productos` SET `pais_origen` = 'IN' WHERE (`pais_origen` = "India");
UPDATE `productos` SET `pais_origen` = 'ID' WHERE (`pais_origen` = "Indonesia");
UPDATE `productos` SET `pais_origen` = 'IR' WHERE (`pais_origen` = "Iran, Islamic Republic of");
UPDATE `productos` SET `pais_origen` = 'IQ' WHERE (`pais_origen` = "Iraq");
UPDATE `productos` SET `pais_origen` = 'IE' WHERE (`pais_origen` = "Ireland");
UPDATE `productos` SET `pais_origen` = 'IM' WHERE (`pais_origen` = "Isle of Man");
UPDATE `productos` SET `pais_origen` = 'IL' WHERE (`pais_origen` = "Israel");
UPDATE `productos` SET `pais_origen` = 'IT' WHERE (`pais_origen` = "Italy");
UPDATE `productos` SET `pais_origen` = 'JM' WHERE (`pais_origen` = "Jamaica");
UPDATE `productos` SET `pais_origen` = 'JP' WHERE (`pais_origen` = "Japan");
UPDATE `productos` SET `pais_origen` = 'JE' WHERE (`pais_origen` = "Jersey");
UPDATE `productos` SET `pais_origen` = 'JO' WHERE (`pais_origen` = "Jordan");
UPDATE `productos` SET `pais_origen` = 'KZ' WHERE (`pais_origen` = "Kazakstan");
UPDATE `productos` SET `pais_origen` = 'KE' WHERE (`pais_origen` = "Kenya");
UPDATE `productos` SET `pais_origen` = 'KI' WHERE (`pais_origen` = "Kiribati");
UPDATE `productos` SET `pais_origen` = 'KP' WHERE (`pais_origen` = "Korea, Democratic People's Republic of");
UPDATE `productos` SET `pais_origen` = 'KR' WHERE (`pais_origen` = "Korea, Republic of");
UPDATE `productos` SET `pais_origen` = 'KW' WHERE (`pais_origen` = "Kuwait");
UPDATE `productos` SET `pais_origen` = 'KG' WHERE (`pais_origen` = "Kyrgyzstan");
UPDATE `productos` SET `pais_origen` = 'LA' WHERE (`pais_origen` = "Lao, People's Democratic Republic");
UPDATE `productos` SET `pais_origen` = 'LV' WHERE (`pais_origen` = "Latvia");
UPDATE `productos` SET `pais_origen` = 'LB' WHERE (`pais_origen` = "Lebanon");
UPDATE `productos` SET `pais_origen` = 'LS' WHERE (`pais_origen` = "Lesotho");
UPDATE `productos` SET `pais_origen` = 'LR' WHERE (`pais_origen` = "Liberia");
UPDATE `productos` SET `pais_origen` = 'LY' WHERE (`pais_origen` = "Libyan Arab Jamahiriya");
UPDATE `productos` SET `pais_origen` = 'LI' WHERE (`pais_origen` = "Liechtenstein");
UPDATE `productos` SET `pais_origen` = 'LT' WHERE (`pais_origen` = "Lithuania");
UPDATE `productos` SET `pais_origen` = 'LU' WHERE (`pais_origen` = "Luxembourg");
UPDATE `productos` SET `pais_origen` = 'MO' WHERE (`pais_origen` = "Macao");
UPDATE `productos` SET `pais_origen` = 'MK' WHERE (`pais_origen` = "Macedonia, The Former Yugoslav Republic Of");
UPDATE `productos` SET `pais_origen` = 'MG' WHERE (`pais_origen` = "Madagascar");
UPDATE `productos` SET `pais_origen` = 'MW' WHERE (`pais_origen` = "Malawi");
UPDATE `productos` SET `pais_origen` = 'MY' WHERE (`pais_origen` = "Malaysia");
UPDATE `productos` SET `pais_origen` = 'MV' WHERE (`pais_origen` = "Maldives");
UPDATE `productos` SET `pais_origen` = 'ML' WHERE (`pais_origen` = "Mali");
UPDATE `productos` SET `pais_origen` = 'MT' WHERE (`pais_origen` = "Malta");
UPDATE `productos` SET `pais_origen` = 'MH' WHERE (`pais_origen` = "Marshall Islands");
UPDATE `productos` SET `pais_origen` = 'MQ' WHERE (`pais_origen` = "Martinique");
UPDATE `productos` SET `pais_origen` = 'MR' WHERE (`pais_origen` = "Mauritania");
UPDATE `productos` SET `pais_origen` = 'MU' WHERE (`pais_origen` = "Mauritius");
UPDATE `productos` SET `pais_origen` = 'YT' WHERE (`pais_origen` = "Mayotte");
UPDATE `productos` SET `pais_origen` = 'MX' WHERE (`pais_origen` = "Mexico");
UPDATE `productos` SET `pais_origen` = 'FM' WHERE (`pais_origen` = "Micronesia, Federated States of");
UPDATE `productos` SET `pais_origen` = 'MD' WHERE (`pais_origen` = "Moldova, Republic of");
UPDATE `productos` SET `pais_origen` = 'MC' WHERE (`pais_origen` = "Monaco");
UPDATE `productos` SET `pais_origen` = 'MN' WHERE (`pais_origen` = "Mongolia");
UPDATE `productos` SET `pais_origen` = 'ME' WHERE (`pais_origen` = "Montenegro");
UPDATE `productos` SET `pais_origen` = 'MS' WHERE (`pais_origen` = "Montserrat");
UPDATE `productos` SET `pais_origen` = 'MA' WHERE (`pais_origen` = "Morocco");
UPDATE `productos` SET `pais_origen` = 'MZ' WHERE (`pais_origen` = "Mozambique");
UPDATE `productos` SET `pais_origen` = 'MM' WHERE (`pais_origen` = "Myanmar");
UPDATE `productos` SET `pais_origen` = 'NA' WHERE (`pais_origen` = "Namibia");
UPDATE `productos` SET `pais_origen` = 'NR' WHERE (`pais_origen` = "Nauru");
UPDATE `productos` SET `pais_origen` = 'NP' WHERE (`pais_origen` = "Nepal");
UPDATE `productos` SET `pais_origen` = 'NL' WHERE (`pais_origen` = "Netherlands");
UPDATE `productos` SET `pais_origen` = 'NC' WHERE (`pais_origen` = "New Caledonia");
UPDATE `productos` SET `pais_origen` = 'NZ' WHERE (`pais_origen` = "New Zealand");
UPDATE `productos` SET `pais_origen` = 'NI' WHERE (`pais_origen` = "Nicaragua");
UPDATE `productos` SET `pais_origen` = 'NE' WHERE (`pais_origen` = "Niger");
UPDATE `productos` SET `pais_origen` = 'NG' WHERE (`pais_origen` = "Nigeria");
UPDATE `productos` SET `pais_origen` = 'NU' WHERE (`pais_origen` = "Niue");
UPDATE `productos` SET `pais_origen` = 'NF' WHERE (`pais_origen` = "Norfolk Island");
UPDATE `productos` SET `pais_origen` = 'MP' WHERE (`pais_origen` = "Northern Mariana Islands");
UPDATE `productos` SET `pais_origen` = 'NO' WHERE (`pais_origen` = "Norway");
UPDATE `productos` SET `pais_origen` = 'OM' WHERE (`pais_origen` = "Oman");
UPDATE `productos` SET `pais_origen` = 'PK' WHERE (`pais_origen` = "Pakistan");
UPDATE `productos` SET `pais_origen` = 'PW' WHERE (`pais_origen` = "Palau");
UPDATE `productos` SET `pais_origen` = 'PS' WHERE (`pais_origen` = "Palestinian Territory, Occupied");
UPDATE `productos` SET `pais_origen` = 'PA' WHERE (`pais_origen` = "Panama");
UPDATE `productos` SET `pais_origen` = 'PG' WHERE (`pais_origen` = "Papua New Guinea");
UPDATE `productos` SET `pais_origen` = 'PY' WHERE (`pais_origen` = "Paraguay");
UPDATE `productos` SET `pais_origen` = 'PE' WHERE (`pais_origen` = "Peru");
UPDATE `productos` SET `pais_origen` = 'PH' WHERE (`pais_origen` = "Philippines");
UPDATE `productos` SET `pais_origen` = 'PN' WHERE (`pais_origen` = "Pitcairn");
UPDATE `productos` SET `pais_origen` = 'PL' WHERE (`pais_origen` = "Poland");
UPDATE `productos` SET `pais_origen` = 'PT' WHERE (`pais_origen` = "Portugal");
UPDATE `productos` SET `pais_origen` = 'PR' WHERE (`pais_origen` = "Puerto Rico");
UPDATE `productos` SET `pais_origen` = 'QA' WHERE (`pais_origen` = "Qatar");
UPDATE `productos` SET `pais_origen` = 'RE' WHERE (`pais_origen` = "Reunion");
UPDATE `productos` SET `pais_origen` = 'RO' WHERE (`pais_origen` = "Romania");
UPDATE `productos` SET `pais_origen` = 'RU' WHERE (`pais_origen` = "Russia Federation");
UPDATE `productos` SET `pais_origen` = 'RW' WHERE (`pais_origen` = "Rwanda");
UPDATE `productos` SET `pais_origen` = 'BL' WHERE (`pais_origen` = "Saint Barthélemy");
UPDATE `productos` SET `pais_origen` = 'SH' WHERE (`pais_origen` = "Saint Helena");
UPDATE `productos` SET `pais_origen` = 'KN' WHERE (`pais_origen` = "Saint Kitts & Nevis");
UPDATE `productos` SET `pais_origen` = 'LC' WHERE (`pais_origen` = "Saint Lucia");
UPDATE `productos` SET `pais_origen` = 'MF' WHERE (`pais_origen` = "Saint Martin");
UPDATE `productos` SET `pais_origen` = 'PM' WHERE (`pais_origen` = "Saint Pierre and Miquelon");
UPDATE `productos` SET `pais_origen` = 'VC' WHERE (`pais_origen` = "Saint Vincent and the Grenadines");
UPDATE `productos` SET `pais_origen` = 'WS' WHERE (`pais_origen` = "Samoa");
UPDATE `productos` SET `pais_origen` = 'SM' WHERE (`pais_origen` = "San Marino");
UPDATE `productos` SET `pais_origen` = 'ST' WHERE (`pais_origen` = "Sao Tome and Principe");
UPDATE `productos` SET `pais_origen` = 'SA' WHERE (`pais_origen` = "Saudi Arabia");
UPDATE `productos` SET `pais_origen` = 'SN' WHERE (`pais_origen` = "Senegal");
UPDATE `productos` SET `pais_origen` = 'RS' WHERE (`pais_origen` = "Serbia and Montenegro");
UPDATE `productos` SET `pais_origen` = 'SC' WHERE (`pais_origen` = "Seychelles");
UPDATE `productos` SET `pais_origen` = 'SL' WHERE (`pais_origen` = "Sierra Leone");
UPDATE `productos` SET `pais_origen` = 'SG' WHERE (`pais_origen` = "Singapore");
UPDATE `productos` SET `pais_origen` = 'SX' WHERE (`pais_origen` = "Sint Maarten");
UPDATE `productos` SET `pais_origen` = 'SK' WHERE (`pais_origen` = "Slovakia");
UPDATE `productos` SET `pais_origen` = 'SI' WHERE (`pais_origen` = "Slovenia");
UPDATE `productos` SET `pais_origen` = 'SB' WHERE (`pais_origen` = "Solomon Islands");
UPDATE `productos` SET `pais_origen` = 'SO' WHERE (`pais_origen` = "Somalia");
UPDATE `productos` SET `pais_origen` = 'ZA' WHERE (`pais_origen` = "South Africa");
UPDATE `productos` SET `pais_origen` = 'GS' WHERE (`pais_origen` = "South Georgia & The South Sandwich Islands");
UPDATE `productos` SET `pais_origen` = 'SS' WHERE (`pais_origen` = "South Sudan");
UPDATE `productos` SET `pais_origen` = 'ES' WHERE (`pais_origen` = "Spain");
UPDATE `productos` SET `pais_origen` = 'LK' WHERE (`pais_origen` = "Sri Lanka");
UPDATE `productos` SET `pais_origen` = 'SD' WHERE (`pais_origen` = "Sudan");
UPDATE `productos` SET `pais_origen` = 'SR' WHERE (`pais_origen` = "Suriname");
UPDATE `productos` SET `pais_origen` = 'SJ' WHERE (`pais_origen` = "Svalbard and Jan Mayen");
UPDATE `productos` SET `pais_origen` = 'SE' WHERE (`pais_origen` = "Sweden");
UPDATE `productos` SET `pais_origen` = 'CH' WHERE (`pais_origen` = "Switzerland");
UPDATE `productos` SET `pais_origen` = 'SY' WHERE (`pais_origen` = "Syrian Arab Republic");
UPDATE `productos` SET `pais_origen` = 'TW' WHERE (`pais_origen` = "Taiwan, Province of China");
UPDATE `productos` SET `pais_origen` = 'TJ' WHERE (`pais_origen` = "Tajikistan");
UPDATE `productos` SET `pais_origen` = 'TZ' WHERE (`pais_origen` = "Tanzania, United Republic of");
UPDATE `productos` SET `pais_origen` = 'TH' WHERE (`pais_origen` = "Thailand");
UPDATE `productos` SET `pais_origen` = 'TL' WHERE (`pais_origen` = "Timor-Leste");
UPDATE `productos` SET `pais_origen` = 'TG' WHERE (`pais_origen` = "Togo");
UPDATE `productos` SET `pais_origen` = 'TK' WHERE (`pais_origen` = "Tokelau");
UPDATE `productos` SET `pais_origen` = 'TO' WHERE (`pais_origen` = "Tonga");
UPDATE `productos` SET `pais_origen` = 'TT' WHERE (`pais_origen` = "Trinidad and Tobago");
UPDATE `productos` SET `pais_origen` = 'TN' WHERE (`pais_origen` = "Tunisia");
UPDATE `productos` SET `pais_origen` = 'TR' WHERE (`pais_origen` = "Turkey");
UPDATE `productos` SET `pais_origen` = 'TM' WHERE (`pais_origen` = "Turkmenistan");
UPDATE `productos` SET `pais_origen` = 'TC' WHERE (`pais_origen` = "Turks and Caicos Islands");
UPDATE `productos` SET `pais_origen` = 'TV' WHERE (`pais_origen` = "Tuvalu");
UPDATE `productos` SET `pais_origen` = 'UG' WHERE (`pais_origen` = "Uganda");
UPDATE `productos` SET `pais_origen` = 'UA' WHERE (`pais_origen` = "Ukraine");
UPDATE `productos` SET `pais_origen` = 'AE' WHERE (`pais_origen` = "United Arab Emirates");
UPDATE `productos` SET `pais_origen` = 'GB' WHERE (`pais_origen` = "United Kingdom");
UPDATE `productos` SET `pais_origen` = 'US' WHERE (`pais_origen` = "United States");
UPDATE `productos` SET `pais_origen` = 'UM' WHERE (`pais_origen` = "United States Minor Outlying Islands");
UPDATE `productos` SET `pais_origen` = 'UY' WHERE (`pais_origen` = "Uruguay");
UPDATE `productos` SET `pais_origen` = 'UZ' WHERE (`pais_origen` = "Uzbekistan");
UPDATE `productos` SET `pais_origen` = 'VU' WHERE (`pais_origen` = "Vanuatu");
UPDATE `productos` SET `pais_origen` = 'VE' WHERE (`pais_origen` = "Venezuela");
UPDATE `productos` SET `pais_origen` = 'VN' WHERE (`pais_origen` = "Vietnam");
UPDATE `productos` SET `pais_origen` = 'VG' WHERE (`pais_origen` = "Virgin Islands, British");
UPDATE `productos` SET `pais_origen` = 'VI' WHERE (`pais_origen` = "Virgin Islands, U.S.");
UPDATE `productos` SET `pais_origen` = 'WF' WHERE (`pais_origen` = "Wallis and Futuna");
UPDATE `productos` SET `pais_origen` = 'EH' WHERE (`pais_origen` = "Western Sahara");
UPDATE `productos` SET `pais_origen` = 'YE' WHERE (`pais_origen` = "Yemen");
UPDATE `productos` SET `pais_origen` = 'ZM' WHERE (`pais_origen` = "Zambia");
UPDATE `productos` SET `pais_origen` = 'ZW' WHERE (`pais_origen` = "Zimbabwe");

/** Modificacion Mercado Objetivo **/

UPDATE `productos` SET `mercado_objetivo` = 'AF' WHERE (`mercado_objetivo` = "Afghanistan");
UPDATE `productos` SET `mercado_objetivo` = 'AX' WHERE (`mercado_objetivo` = "Aland Islands");
UPDATE `productos` SET `mercado_objetivo` = 'AL' WHERE (`mercado_objetivo` = "Albania");
UPDATE `productos` SET `mercado_objetivo` = 'DZ' WHERE (`mercado_objetivo` = "Algeria");
UPDATE `productos` SET `mercado_objetivo` = 'AS' WHERE (`mercado_objetivo` = "American Samoa");
UPDATE `productos` SET `mercado_objetivo` = 'AD' WHERE (`mercado_objetivo` = "Andorra");
UPDATE `productos` SET `mercado_objetivo` = 'AO' WHERE (`mercado_objetivo` = "Angola");
UPDATE `productos` SET `mercado_objetivo` = 'AI' WHERE (`mercado_objetivo` = "Anguilla");
UPDATE `productos` SET `mercado_objetivo` = 'AQ' WHERE (`mercado_objetivo` = "Antarctica");
UPDATE `productos` SET `mercado_objetivo` = 'AG' WHERE (`mercado_objetivo` = "Antigua and Barbuda");
UPDATE `productos` SET `mercado_objetivo` = 'AR' WHERE (`mercado_objetivo` = "Argentina");
UPDATE `productos` SET `mercado_objetivo` = 'AM' WHERE (`mercado_objetivo` = "Armenia");
UPDATE `productos` SET `mercado_objetivo` = 'AW' WHERE (`mercado_objetivo` = "Aruba");
UPDATE `productos` SET `mercado_objetivo` = 'AU' WHERE (`mercado_objetivo` = "Australia");
UPDATE `productos` SET `mercado_objetivo` = 'AT' WHERE (`mercado_objetivo` = "Austria");
UPDATE `productos` SET `mercado_objetivo` = 'AZ' WHERE (`mercado_objetivo` = "Azerbaijan");
UPDATE `productos` SET `mercado_objetivo` = 'BS' WHERE (`mercado_objetivo` = "Bahamas");
UPDATE `productos` SET `mercado_objetivo` = 'BH' WHERE (`mercado_objetivo` = "Bahrain");
UPDATE `productos` SET `mercado_objetivo` = 'BD' WHERE (`mercado_objetivo` = "Bangladesh");
UPDATE `productos` SET `mercado_objetivo` = 'BB' WHERE (`mercado_objetivo` = "Barbados");
UPDATE `productos` SET `mercado_objetivo` = 'BY' WHERE (`mercado_objetivo` = "Belarus");
UPDATE `productos` SET `mercado_objetivo` = 'BE' WHERE (`mercado_objetivo` = "Belgium");
UPDATE `productos` SET `mercado_objetivo` = 'BZ' WHERE (`mercado_objetivo` = "Belize");
UPDATE `productos` SET `mercado_objetivo` = 'BJ' WHERE (`mercado_objetivo` = "Benin");
UPDATE `productos` SET `mercado_objetivo` = 'BM' WHERE (`mercado_objetivo` = "Bermuda");
UPDATE `productos` SET `mercado_objetivo` = 'BT' WHERE (`mercado_objetivo` = "Bhutan");
UPDATE `productos` SET `mercado_objetivo` = 'BO' WHERE (`mercado_objetivo` = "Bolivia");
UPDATE `productos` SET `mercado_objetivo` = 'BQ' WHERE (`mercado_objetivo` = "Bonaire, Sint Eustatius and Saba");
UPDATE `productos` SET `mercado_objetivo` = 'BA' WHERE (`mercado_objetivo` = "Bosnia and Herzegovina");
UPDATE `productos` SET `mercado_objetivo` = 'BW' WHERE (`mercado_objetivo` = "Botswana");
UPDATE `productos` SET `mercado_objetivo` = 'BV' WHERE (`mercado_objetivo` = "Bouvet Island");
UPDATE `productos` SET `mercado_objetivo` = 'BR' WHERE (`mercado_objetivo` = "Brazil");
UPDATE `productos` SET `mercado_objetivo` = 'BR' WHERE (`mercado_objetivo` = "Brasil");
UPDATE `productos` SET `mercado_objetivo` = 'IO' WHERE (`mercado_objetivo` = "British Indian Ocean Territory");
UPDATE `productos` SET `mercado_objetivo` = 'BN' WHERE (`mercado_objetivo` = "Brunei Darussalam");
UPDATE `productos` SET `mercado_objetivo` = 'BG' WHERE (`mercado_objetivo` = "Bulgaria");
UPDATE `productos` SET `mercado_objetivo` = 'BF' WHERE (`mercado_objetivo` = "Burkina Faso");
UPDATE `productos` SET `mercado_objetivo` = 'BI' WHERE (`mercado_objetivo` = "Burundi");
UPDATE `productos` SET `mercado_objetivo` = 'CV' WHERE (`mercado_objetivo` = "Cambodia");
UPDATE `productos` SET `mercado_objetivo` = 'KH' WHERE (`mercado_objetivo` = "Cameroon");
UPDATE `productos` SET `mercado_objetivo` = 'CM' WHERE (`mercado_objetivo` = "Canada");
UPDATE `productos` SET `mercado_objetivo` = 'CA' WHERE (`mercado_objetivo` = "Cape Verde");
UPDATE `productos` SET `mercado_objetivo` = 'KY' WHERE (`mercado_objetivo` = "Cayman Islands");
UPDATE `productos` SET `mercado_objetivo` = 'CF' WHERE (`mercado_objetivo` = "Central African Republic");
UPDATE `productos` SET `mercado_objetivo` = 'TD' WHERE (`mercado_objetivo` = "Chad");
UPDATE `productos` SET `mercado_objetivo` = 'CL' WHERE (`mercado_objetivo` = "Chile");
UPDATE `productos` SET `mercado_objetivo` = 'CN' WHERE (`mercado_objetivo` = "China");
UPDATE `productos` SET `mercado_objetivo` = 'CX' WHERE (`mercado_objetivo` = "Christmas Island");
UPDATE `productos` SET `mercado_objetivo` = 'CC' WHERE (`mercado_objetivo` = "Cocos (Keeling) Islands");
UPDATE `productos` SET `mercado_objetivo` = 'CO' WHERE (`mercado_objetivo` = "Colombia");
UPDATE `productos` SET `mercado_objetivo` = 'KM' WHERE (`mercado_objetivo` = "Comoros");
UPDATE `productos` SET `mercado_objetivo` = 'CD' WHERE (`mercado_objetivo` = "Congo");
UPDATE `productos` SET `mercado_objetivo` = 'CG' WHERE (`mercado_objetivo` = "Congo, The Democratic Republic of ");
UPDATE `productos` SET `mercado_objetivo` = 'CK' WHERE (`mercado_objetivo` = "Cook Islands");
UPDATE `productos` SET `mercado_objetivo` = 'CR' WHERE (`mercado_objetivo` = "Costa Rica");
UPDATE `productos` SET `mercado_objetivo` = 'CI' WHERE (`mercado_objetivo` = "Cote d'Ivoire");
UPDATE `productos` SET `mercado_objetivo` = 'HR' WHERE (`mercado_objetivo` = "Croatia");
UPDATE `productos` SET `mercado_objetivo` = 'CU' WHERE (`mercado_objetivo` = "Cuba");
UPDATE `productos` SET `mercado_objetivo` = 'CW' WHERE (`mercado_objetivo` = "Curaçao");
UPDATE `productos` SET `mercado_objetivo` = 'CY' WHERE (`mercado_objetivo` = "Cyprus");
UPDATE `productos` SET `mercado_objetivo` = 'CZ' WHERE (`mercado_objetivo` = "Czechia");
UPDATE `productos` SET `mercado_objetivo` = 'DK' WHERE (`mercado_objetivo` = "Denmark");
UPDATE `productos` SET `mercado_objetivo` = 'DJ' WHERE (`mercado_objetivo` = "Djibouti");
UPDATE `productos` SET `mercado_objetivo` = 'DM' WHERE (`mercado_objetivo` = "Dominica");
UPDATE `productos` SET `mercado_objetivo` = 'DO' WHERE (`mercado_objetivo` = "Dominican Republic");
UPDATE `productos` SET `mercado_objetivo` = 'EC' WHERE (`mercado_objetivo` = "Ecuador");
UPDATE `productos` SET `mercado_objetivo` = 'EG' WHERE (`mercado_objetivo` = "Egypt");
UPDATE `productos` SET `mercado_objetivo` = 'SV' WHERE (`mercado_objetivo` = "El Salvador");
UPDATE `productos` SET `mercado_objetivo` = 'GQ' WHERE (`mercado_objetivo` = "Equatorial Guinea");
UPDATE `productos` SET `mercado_objetivo` = 'ER' WHERE (`mercado_objetivo` = "Eritrea");
UPDATE `productos` SET `mercado_objetivo` = 'EE' WHERE (`mercado_objetivo` = "Estonia");
UPDATE `productos` SET `mercado_objetivo` = 'ET' WHERE (`mercado_objetivo` = "Ethiopia");
UPDATE `productos` SET `mercado_objetivo` = 'FK' WHERE (`mercado_objetivo` = "Falkland Islands (Malvinas)");
UPDATE `productos` SET `mercado_objetivo` = 'FO' WHERE (`mercado_objetivo` = "Faroe Islands");
UPDATE `productos` SET `mercado_objetivo` = 'FJ' WHERE (`mercado_objetivo` = "Fiji");
UPDATE `productos` SET `mercado_objetivo` = 'FI' WHERE (`mercado_objetivo` = "Finland");
UPDATE `productos` SET `mercado_objetivo` = 'FR' WHERE (`mercado_objetivo` = "France");
UPDATE `productos` SET `mercado_objetivo` = 'GF' WHERE (`mercado_objetivo` = "French Guiana");
UPDATE `productos` SET `mercado_objetivo` = 'PF' WHERE (`mercado_objetivo` = "French Polynesia");
UPDATE `productos` SET `mercado_objetivo` = 'TF' WHERE (`mercado_objetivo` = "French Southern Territories");
UPDATE `productos` SET `mercado_objetivo` = 'GA' WHERE (`mercado_objetivo` = "Gabon");
UPDATE `productos` SET `mercado_objetivo` = 'GM' WHERE (`mercado_objetivo` = "Gambia");
UPDATE `productos` SET `mercado_objetivo` = 'GE' WHERE (`mercado_objetivo` = "Georgia");
UPDATE `productos` SET `mercado_objetivo` = 'DE' WHERE (`mercado_objetivo` = "Germany");
UPDATE `productos` SET `mercado_objetivo` = 'GH' WHERE (`mercado_objetivo` = "Ghana");
UPDATE `productos` SET `mercado_objetivo` = 'GI' WHERE (`mercado_objetivo` = "Gibraltar");
UPDATE `productos` SET `mercado_objetivo` = 'GR' WHERE (`mercado_objetivo` = "Greece");
UPDATE `productos` SET `mercado_objetivo` = 'GL' WHERE (`mercado_objetivo` = "Greenland");
UPDATE `productos` SET `mercado_objetivo` = 'GD' WHERE (`mercado_objetivo` = "Grenada");
UPDATE `productos` SET `mercado_objetivo` = 'GP' WHERE (`mercado_objetivo` = "Guadeloupe");
UPDATE `productos` SET `mercado_objetivo` = 'GU' WHERE (`mercado_objetivo` = "Guam");
UPDATE `productos` SET `mercado_objetivo` = 'GT' WHERE (`mercado_objetivo` = "Guatemala");
UPDATE `productos` SET `mercado_objetivo` = 'GG' WHERE (`mercado_objetivo` = "Guernsey");
UPDATE `productos` SET `mercado_objetivo` = 'GN' WHERE (`mercado_objetivo` = "Guinea");
UPDATE `productos` SET `mercado_objetivo` = 'GW' WHERE (`mercado_objetivo` = "Guinea-Bissau");
UPDATE `productos` SET `mercado_objetivo` = 'GY' WHERE (`mercado_objetivo` = "Guyana");
UPDATE `productos` SET `mercado_objetivo` = 'HT' WHERE (`mercado_objetivo` = "Haiti");
UPDATE `productos` SET `mercado_objetivo` = 'HM' WHERE (`mercado_objetivo` = "Heard and Mc Donald Islands");
UPDATE `productos` SET `mercado_objetivo` = 'VA' WHERE (`mercado_objetivo` = "Holy See (Vatican City State)");
UPDATE `productos` SET `mercado_objetivo` = 'HN' WHERE (`mercado_objetivo` = "Honduras");
UPDATE `productos` SET `mercado_objetivo` = 'HK' WHERE (`mercado_objetivo` = "Hong Kong");
UPDATE `productos` SET `mercado_objetivo` = 'HU' WHERE (`mercado_objetivo` = "Hungary");
UPDATE `productos` SET `mercado_objetivo` = 'IS' WHERE (`mercado_objetivo` = "Iceland");
UPDATE `productos` SET `mercado_objetivo` = 'IN' WHERE (`mercado_objetivo` = "India");
UPDATE `productos` SET `mercado_objetivo` = 'ID' WHERE (`mercado_objetivo` = "Indonesia");
UPDATE `productos` SET `mercado_objetivo` = 'IR' WHERE (`mercado_objetivo` = "Iran, Islamic Republic of");
UPDATE `productos` SET `mercado_objetivo` = 'IQ' WHERE (`mercado_objetivo` = "Iraq");
UPDATE `productos` SET `mercado_objetivo` = 'IE' WHERE (`mercado_objetivo` = "Ireland");
UPDATE `productos` SET `mercado_objetivo` = 'IM' WHERE (`mercado_objetivo` = "Isle of Man");
UPDATE `productos` SET `mercado_objetivo` = 'IL' WHERE (`mercado_objetivo` = "Israel");
UPDATE `productos` SET `mercado_objetivo` = 'IT' WHERE (`mercado_objetivo` = "Italy");
UPDATE `productos` SET `mercado_objetivo` = 'JM' WHERE (`mercado_objetivo` = "Jamaica");
UPDATE `productos` SET `mercado_objetivo` = 'JP' WHERE (`mercado_objetivo` = "Japan");
UPDATE `productos` SET `mercado_objetivo` = 'JE' WHERE (`mercado_objetivo` = "Jersey");
UPDATE `productos` SET `mercado_objetivo` = 'JO' WHERE (`mercado_objetivo` = "Jordan");
UPDATE `productos` SET `mercado_objetivo` = 'KZ' WHERE (`mercado_objetivo` = "Kazakstan");
UPDATE `productos` SET `mercado_objetivo` = 'KE' WHERE (`mercado_objetivo` = "Kenya");
UPDATE `productos` SET `mercado_objetivo` = 'KI' WHERE (`mercado_objetivo` = "Kiribati");
UPDATE `productos` SET `mercado_objetivo` = 'KP' WHERE (`mercado_objetivo` = "Korea, Democratic People's Republic of");
UPDATE `productos` SET `mercado_objetivo` = 'KR' WHERE (`mercado_objetivo` = "Korea, Republic of");
UPDATE `productos` SET `mercado_objetivo` = 'KW' WHERE (`mercado_objetivo` = "Kuwait");
UPDATE `productos` SET `mercado_objetivo` = 'KG' WHERE (`mercado_objetivo` = "Kyrgyzstan");
UPDATE `productos` SET `mercado_objetivo` = 'LA' WHERE (`mercado_objetivo` = "Lao, People's Democratic Republic");
UPDATE `productos` SET `mercado_objetivo` = 'LV' WHERE (`mercado_objetivo` = "Latvia");
UPDATE `productos` SET `mercado_objetivo` = 'LB' WHERE (`mercado_objetivo` = "Lebanon");
UPDATE `productos` SET `mercado_objetivo` = 'LS' WHERE (`mercado_objetivo` = "Lesotho");
UPDATE `productos` SET `mercado_objetivo` = 'LR' WHERE (`mercado_objetivo` = "Liberia");
UPDATE `productos` SET `mercado_objetivo` = 'LY' WHERE (`mercado_objetivo` = "Libyan Arab Jamahiriya");
UPDATE `productos` SET `mercado_objetivo` = 'LI' WHERE (`mercado_objetivo` = "Liechtenstein");
UPDATE `productos` SET `mercado_objetivo` = 'LT' WHERE (`mercado_objetivo` = "Lithuania");
UPDATE `productos` SET `mercado_objetivo` = 'LU' WHERE (`mercado_objetivo` = "Luxembourg");
UPDATE `productos` SET `mercado_objetivo` = 'MO' WHERE (`mercado_objetivo` = "Macao");
UPDATE `productos` SET `mercado_objetivo` = 'MK' WHERE (`mercado_objetivo` = "Macedonia, The Former Yugoslav Republic Of");
UPDATE `productos` SET `mercado_objetivo` = 'MG' WHERE (`mercado_objetivo` = "Madagascar");
UPDATE `productos` SET `mercado_objetivo` = 'MW' WHERE (`mercado_objetivo` = "Malawi");
UPDATE `productos` SET `mercado_objetivo` = 'MY' WHERE (`mercado_objetivo` = "Malaysia");
UPDATE `productos` SET `mercado_objetivo` = 'MV' WHERE (`mercado_objetivo` = "Maldives");
UPDATE `productos` SET `mercado_objetivo` = 'ML' WHERE (`mercado_objetivo` = "Mali");
UPDATE `productos` SET `mercado_objetivo` = 'MT' WHERE (`mercado_objetivo` = "Malta");
UPDATE `productos` SET `mercado_objetivo` = 'MH' WHERE (`mercado_objetivo` = "Marshall Islands");
UPDATE `productos` SET `mercado_objetivo` = 'MQ' WHERE (`mercado_objetivo` = "Martinique");
UPDATE `productos` SET `mercado_objetivo` = 'MR' WHERE (`mercado_objetivo` = "Mauritania");
UPDATE `productos` SET `mercado_objetivo` = 'MU' WHERE (`mercado_objetivo` = "Mauritius");
UPDATE `productos` SET `mercado_objetivo` = 'YT' WHERE (`mercado_objetivo` = "Mayotte");
UPDATE `productos` SET `mercado_objetivo` = 'MX' WHERE (`mercado_objetivo` = "Mexico");
UPDATE `productos` SET `mercado_objetivo` = 'FM' WHERE (`mercado_objetivo` = "Micronesia, Federated States of");
UPDATE `productos` SET `mercado_objetivo` = 'MD' WHERE (`mercado_objetivo` = "Moldova, Republic of");
UPDATE `productos` SET `mercado_objetivo` = 'MC' WHERE (`mercado_objetivo` = "Monaco");
UPDATE `productos` SET `mercado_objetivo` = 'MN' WHERE (`mercado_objetivo` = "Mongolia");
UPDATE `productos` SET `mercado_objetivo` = 'ME' WHERE (`mercado_objetivo` = "Montenegro");
UPDATE `productos` SET `mercado_objetivo` = 'MS' WHERE (`mercado_objetivo` = "Montserrat");
UPDATE `productos` SET `mercado_objetivo` = 'MA' WHERE (`mercado_objetivo` = "Morocco");
UPDATE `productos` SET `mercado_objetivo` = 'MZ' WHERE (`mercado_objetivo` = "Mozambique");
UPDATE `productos` SET `mercado_objetivo` = 'MM' WHERE (`mercado_objetivo` = "Myanmar");
UPDATE `productos` SET `mercado_objetivo` = 'NA' WHERE (`mercado_objetivo` = "Namibia");
UPDATE `productos` SET `mercado_objetivo` = 'NR' WHERE (`mercado_objetivo` = "Nauru");
UPDATE `productos` SET `mercado_objetivo` = 'NP' WHERE (`mercado_objetivo` = "Nepal");
UPDATE `productos` SET `mercado_objetivo` = 'NL' WHERE (`mercado_objetivo` = "Netherlands");
UPDATE `productos` SET `mercado_objetivo` = 'NC' WHERE (`mercado_objetivo` = "New Caledonia");
UPDATE `productos` SET `mercado_objetivo` = 'NZ' WHERE (`mercado_objetivo` = "New Zealand");
UPDATE `productos` SET `mercado_objetivo` = 'NI' WHERE (`mercado_objetivo` = "Nicaragua");
UPDATE `productos` SET `mercado_objetivo` = 'NE' WHERE (`mercado_objetivo` = "Niger");
UPDATE `productos` SET `mercado_objetivo` = 'NG' WHERE (`mercado_objetivo` = "Nigeria");
UPDATE `productos` SET `mercado_objetivo` = 'NU' WHERE (`mercado_objetivo` = "Niue");
UPDATE `productos` SET `mercado_objetivo` = 'NF' WHERE (`mercado_objetivo` = "Norfolk Island");
UPDATE `productos` SET `mercado_objetivo` = 'MP' WHERE (`mercado_objetivo` = "Northern Mariana Islands");
UPDATE `productos` SET `mercado_objetivo` = 'NO' WHERE (`mercado_objetivo` = "Norway");
UPDATE `productos` SET `mercado_objetivo` = 'OM' WHERE (`mercado_objetivo` = "Oman");
UPDATE `productos` SET `mercado_objetivo` = 'PK' WHERE (`mercado_objetivo` = "Pakistan");
UPDATE `productos` SET `mercado_objetivo` = 'PW' WHERE (`mercado_objetivo` = "Palau");
UPDATE `productos` SET `mercado_objetivo` = 'PS' WHERE (`mercado_objetivo` = "Palestinian Territory, Occupied");
UPDATE `productos` SET `mercado_objetivo` = 'PA' WHERE (`mercado_objetivo` = "Panama");
UPDATE `productos` SET `mercado_objetivo` = 'PG' WHERE (`mercado_objetivo` = "Papua New Guinea");
UPDATE `productos` SET `mercado_objetivo` = 'PY' WHERE (`mercado_objetivo` = "Paraguay");
UPDATE `productos` SET `mercado_objetivo` = 'PE' WHERE (`mercado_objetivo` = "Peru");
UPDATE `productos` SET `mercado_objetivo` = 'PH' WHERE (`mercado_objetivo` = "Philippines");
UPDATE `productos` SET `mercado_objetivo` = 'PN' WHERE (`mercado_objetivo` = "Pitcairn");
UPDATE `productos` SET `mercado_objetivo` = 'PL' WHERE (`mercado_objetivo` = "Poland");
UPDATE `productos` SET `mercado_objetivo` = 'PT' WHERE (`mercado_objetivo` = "Portugal");
UPDATE `productos` SET `mercado_objetivo` = 'PR' WHERE (`mercado_objetivo` = "Puerto Rico");
UPDATE `productos` SET `mercado_objetivo` = 'QA' WHERE (`mercado_objetivo` = "Qatar");
UPDATE `productos` SET `mercado_objetivo` = 'RE' WHERE (`mercado_objetivo` = "Reunion");
UPDATE `productos` SET `mercado_objetivo` = 'RO' WHERE (`mercado_objetivo` = "Romania");
UPDATE `productos` SET `mercado_objetivo` = 'RU' WHERE (`mercado_objetivo` = "Russia Federation");
UPDATE `productos` SET `mercado_objetivo` = 'RW' WHERE (`mercado_objetivo` = "Rwanda");
UPDATE `productos` SET `mercado_objetivo` = 'BL' WHERE (`mercado_objetivo` = "Saint Barthélemy");
UPDATE `productos` SET `mercado_objetivo` = 'SH' WHERE (`mercado_objetivo` = "Saint Helena");
UPDATE `productos` SET `mercado_objetivo` = 'KN' WHERE (`mercado_objetivo` = "Saint Kitts & Nevis");
UPDATE `productos` SET `mercado_objetivo` = 'LC' WHERE (`mercado_objetivo` = "Saint Lucia");
UPDATE `productos` SET `mercado_objetivo` = 'MF' WHERE (`mercado_objetivo` = "Saint Martin");
UPDATE `productos` SET `mercado_objetivo` = 'PM' WHERE (`mercado_objetivo` = "Saint Pierre and Miquelon");
UPDATE `productos` SET `mercado_objetivo` = 'VC' WHERE (`mercado_objetivo` = "Saint Vincent and the Grenadines");
UPDATE `productos` SET `mercado_objetivo` = 'WS' WHERE (`mercado_objetivo` = "Samoa");
UPDATE `productos` SET `mercado_objetivo` = 'SM' WHERE (`mercado_objetivo` = "San Marino");
UPDATE `productos` SET `mercado_objetivo` = 'ST' WHERE (`mercado_objetivo` = "Sao Tome and Principe");
UPDATE `productos` SET `mercado_objetivo` = 'SA' WHERE (`mercado_objetivo` = "Saudi Arabia");
UPDATE `productos` SET `mercado_objetivo` = 'SN' WHERE (`mercado_objetivo` = "Senegal");
UPDATE `productos` SET `mercado_objetivo` = 'RS' WHERE (`mercado_objetivo` = "Serbia and Montenegro");
UPDATE `productos` SET `mercado_objetivo` = 'SC' WHERE (`mercado_objetivo` = "Seychelles");
UPDATE `productos` SET `mercado_objetivo` = 'SL' WHERE (`mercado_objetivo` = "Sierra Leone");
UPDATE `productos` SET `mercado_objetivo` = 'SG' WHERE (`mercado_objetivo` = "Singapore");
UPDATE `productos` SET `mercado_objetivo` = 'SX' WHERE (`mercado_objetivo` = "Sint Maarten");
UPDATE `productos` SET `mercado_objetivo` = 'SK' WHERE (`mercado_objetivo` = "Slovakia");
UPDATE `productos` SET `mercado_objetivo` = 'SI' WHERE (`mercado_objetivo` = "Slovenia");
UPDATE `productos` SET `mercado_objetivo` = 'SB' WHERE (`mercado_objetivo` = "Solomon Islands");
UPDATE `productos` SET `mercado_objetivo` = 'SO' WHERE (`mercado_objetivo` = "Somalia");
UPDATE `productos` SET `mercado_objetivo` = 'ZA' WHERE (`mercado_objetivo` = "South Africa");
UPDATE `productos` SET `mercado_objetivo` = 'GS' WHERE (`mercado_objetivo` = "South Georgia & The South Sandwich Islands");
UPDATE `productos` SET `mercado_objetivo` = 'SS' WHERE (`mercado_objetivo` = "South Sudan");
UPDATE `productos` SET `mercado_objetivo` = 'ES' WHERE (`mercado_objetivo` = "Spain");
UPDATE `productos` SET `mercado_objetivo` = 'LK' WHERE (`mercado_objetivo` = "Sri Lanka");
UPDATE `productos` SET `mercado_objetivo` = 'SD' WHERE (`mercado_objetivo` = "Sudan");
UPDATE `productos` SET `mercado_objetivo` = 'SR' WHERE (`mercado_objetivo` = "Suriname");
UPDATE `productos` SET `mercado_objetivo` = 'SJ' WHERE (`mercado_objetivo` = "Svalbard and Jan Mayen");
UPDATE `productos` SET `mercado_objetivo` = 'SE' WHERE (`mercado_objetivo` = "Sweden");
UPDATE `productos` SET `mercado_objetivo` = 'CH' WHERE (`mercado_objetivo` = "Switzerland");
UPDATE `productos` SET `mercado_objetivo` = 'SY' WHERE (`mercado_objetivo` = "Syrian Arab Republic");
UPDATE `productos` SET `mercado_objetivo` = 'TW' WHERE (`mercado_objetivo` = "Taiwan, Province of China");
UPDATE `productos` SET `mercado_objetivo` = 'TJ' WHERE (`mercado_objetivo` = "Tajikistan");
UPDATE `productos` SET `mercado_objetivo` = 'TZ' WHERE (`mercado_objetivo` = "Tanzania, United Republic of");
UPDATE `productos` SET `mercado_objetivo` = 'TH' WHERE (`mercado_objetivo` = "Thailand");
UPDATE `productos` SET `mercado_objetivo` = 'TL' WHERE (`mercado_objetivo` = "Timor-Leste");
UPDATE `productos` SET `mercado_objetivo` = 'TG' WHERE (`mercado_objetivo` = "Togo");
UPDATE `productos` SET `mercado_objetivo` = 'TK' WHERE (`mercado_objetivo` = "Tokelau");
UPDATE `productos` SET `mercado_objetivo` = 'TO' WHERE (`mercado_objetivo` = "Tonga");
UPDATE `productos` SET `mercado_objetivo` = 'TT' WHERE (`mercado_objetivo` = "Trinidad and Tobago");
UPDATE `productos` SET `mercado_objetivo` = 'TN' WHERE (`mercado_objetivo` = "Tunisia");
UPDATE `productos` SET `mercado_objetivo` = 'TR' WHERE (`mercado_objetivo` = "Turkey");
UPDATE `productos` SET `mercado_objetivo` = 'TM' WHERE (`mercado_objetivo` = "Turkmenistan");
UPDATE `productos` SET `mercado_objetivo` = 'TC' WHERE (`mercado_objetivo` = "Turks and Caicos Islands");
UPDATE `productos` SET `mercado_objetivo` = 'TV' WHERE (`mercado_objetivo` = "Tuvalu");
UPDATE `productos` SET `mercado_objetivo` = 'UG' WHERE (`mercado_objetivo` = "Uganda");
UPDATE `productos` SET `mercado_objetivo` = 'UA' WHERE (`mercado_objetivo` = "Ukraine");
UPDATE `productos` SET `mercado_objetivo` = 'AE' WHERE (`mercado_objetivo` = "United Arab Emirates");
UPDATE `productos` SET `mercado_objetivo` = 'GB' WHERE (`mercado_objetivo` = "United Kingdom");
UPDATE `productos` SET `mercado_objetivo` = 'US' WHERE (`mercado_objetivo` = "United States");
UPDATE `productos` SET `mercado_objetivo` = 'UM' WHERE (`mercado_objetivo` = "United States Minor Outlying Islands");
UPDATE `productos` SET `mercado_objetivo` = 'UY' WHERE (`mercado_objetivo` = "Uruguay");
UPDATE `productos` SET `mercado_objetivo` = 'UZ' WHERE (`mercado_objetivo` = "Uzbekistan");
UPDATE `productos` SET `mercado_objetivo` = 'VU' WHERE (`mercado_objetivo` = "Vanuatu");
UPDATE `productos` SET `mercado_objetivo` = 'VE' WHERE (`mercado_objetivo` = "Venezuela");
UPDATE `productos` SET `mercado_objetivo` = 'VN' WHERE (`mercado_objetivo` = "Vietnam");
UPDATE `productos` SET `mercado_objetivo` = 'VG' WHERE (`mercado_objetivo` = "Virgin Islands, British");
UPDATE `productos` SET `mercado_objetivo` = 'VI' WHERE (`mercado_objetivo` = "Virgin Islands, U.S.");
UPDATE `productos` SET `mercado_objetivo` = 'WF' WHERE (`mercado_objetivo` = "Wallis and Futuna");
UPDATE `productos` SET `mercado_objetivo` = 'EH' WHERE (`mercado_objetivo` = "Western Sahara");
UPDATE `productos` SET `mercado_objetivo` = 'YE' WHERE (`mercado_objetivo` = "Yemen");
UPDATE `productos` SET `mercado_objetivo` = 'ZM' WHERE (`mercado_objetivo` = "Zambia");
UPDATE `productos` SET `mercado_objetivo` = 'ZW' WHERE (`mercado_objetivo` = "Zimbabwe");